import HashMap from './Hashmap.js';

const Hash = new HashMap();
Hash.set('Hampus', 'Farn');
Hash.set('Hampus', 'Farner');
Hash.set('Marica', 'Jacobsson');
Hash.set('hampus', 'blabla');
Hash.set('qq', 'ww');
Hash.set('qweee', 'ssw');
Hash.set('qqee', 'szs');
Hash.set('wws', 'a');
Hash.set('wqqhjt', 'ssqwe');
Hash.set('griri', 'gbb');
Hash.set('hhhhee', 'rrrt');
Hash.set('rttred', 'zzz');
Hash.set('zzsdg', 'ww');
Hash.set('eeqwegh', 'eqw');
Hash.set('gdsg', 'sse');
console.log(Hash.entries());
Hash.set('sdf', 'sdf');
Hash.set('sdff', 'w');
Hash.set('szzzzz', 'zasd');
Hash.set('ggjhghj', 'ghjghjjj');
Hash.set('hhhhhhhh', 'gghjg');
Hash.set('ghjttt', 'hcccc');
Hash.set('bvbvbvbv', 'cd');
Hash.set('bfdggggddd', 'dd');
Hash.set('ddg', 'g');
Hash.set('eeeee', 'ssss');
Hash.set('ggehrheh', 'ghhh');
Hash.set('jjj', 'j');
Hash.set('hhhhhhhg', 'hjg');
Hash.set('hjjj', 'j');
Hash.set('hjjaaj', 'j');
Hash.set('hjaawwjj', 'j');
Hash.set('hjaqqjj', 'j');

console.log(Hash.length());
console.log(Hash.entries());
